### ISSUE TITLE
TypeError: n.modInv is not a function

### ISSUE THREAD

**Issue by siabylx** [Sean-Bradley/ECDSA_secp256k1_JordonMatrix_nodejs#3]
line 91 and 92

var div = function (a, n) {
         return from_jordan(jordan_multiply(to_jordan(a), (n.modInv(P)).mod(P)))

"TypeError: n.modInv is not a function"

Ran into this error while playing around with a few variations of formulas. 

I realize I could multiply by the modInv instead of using div as a function, but I wanted to try to use your code to divide 2 separate points... I will play around with this some more to see if I can fix it.

**Comment by Sean-Bradley** [comment]
there is actually another problem with the div function that you've helped me find.
The P should be N
```javascript
var div = function (a, n) {
    return from_jordan(jordan_multiply(to_jordan(a), n.modInv(N).mod(N)))
}
```
I don't think this was your initial error though.
Yours was probably caused by not converting your divisor to a bignumber first.

div needs an ecpoint and a bignumber.
But even if you did convert it, your result would have been wrong since my function was incorrectly  modular inversing P instead of N.
I never picked this up since my demo code wan't actually using the div function at all.

So now my test works,
eg,
```javascript
//1st i create an ecpoint of 10 (secp256k1)
var myECPoint = mul([x, y], new BN(10));
console.log("myECPoint = [" + myECPoint[0].toString(16) + ", " + myECPoint[1].toString(16) + "]")
//next i will divide it by 5. must convert 5 to a bignumber
var ecResult = div(myECPoint, new BN(5))
console.log("ecResult = [" + ecResult[0].toString(16) + ", " + ecResult[1].toString(16) + "]")
//result should equal ecpoint of 2 (secp256k1)
var ecTest = mul([x, y], new BN(2)) //expected result 
console.log(ecResult[0].toString(16) === ecTest[0].toString(16) && ecResult[1].toString(16) === ecTest[1].toString(16))
//should print 'True'
```

I'll atleast push a fix for the div function now.

Thanks
